language: ruby
rvm:
  - 2.0.0
os:
  - linux
  - osx
install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update >/dev/null
    sudo apt-get install -y zsh
  else
    brew update >/dev/null
    brew install shellcheck shfmt zsh
  fi
script:
  - ./script/test
notifications:
  email: false
