language: ruby
rvm:
  - 2.0.0
os:
  - linux
  - osx
install: |
  set -e
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update
    sudo apt-get install -y zsh
  else
    brew install shellcheck shfmt zsh
  fi
  curl -sL https://git.io/shcheck | bash
  zsh --version
script:
  - ./script/test
notifications:
  email: false
