language: bash

install:
  - wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.4-3_amd64.deb
  - sudo dpkg -i shellcheck_0.3.4-3_amd64.deb
  - sudo apt-get update
  - sudo apt-get install -f
  - shellcheck -V
script:
  - ./build.sh
